version: '3'
services:
  nestjs-app:
    build:
      context: .
    ports:
      - '3001:3001'
    container_name: learner-ai
    restart: always
    networks:
      - ai-network
    environment:
      - MONGO_URL=
      - AI4BHARAT_API_KEY=
      - AI4BHARAT_URL=
      - SERVER_URL=
      - ALL_CONTENT_SERVICE_API=
      - ALL_TEXT_EVAL_API=
      - PORT=3001
      - DATABASE=mongodb

networks:
  ai-network:
    driver: bridge
